/**
 * Tests for the rubric-driven manifest summary generator.
 *
 * The summary's _detection_ layer comes from the signals rubric — these tests
 * feed `generateManifestSummary` synthesised `ManifestSignalsResult` values
 * (the same shape the rubric evaluator returns) and assert the resulting
 * sentence + details. Real-world parity is covered separately by the
 * goldens against `__fixtures__/*.signals.json`.
 */
import { describe, expect, it } from 'vitest'
import { generateManifestSummary } from './generateSummary'
import type { CrJsonManifestEntry } from './crjson'
import type { ManifestSignalsResult, SignalHit } from './rubrics/types'

// ── Fixture builders ──────────────────────────────────────────────────

function manifest(overrides: Partial<CrJsonManifestEntry> = {}): CrJsonManifestEntry {
  return {
    label: 'urn:c2pa:test',
    assertions: {},
    ...overrides,
  }
}

function withCert(m: CrJsonManifestEntry, common_name: string, issuer = 'C2PA Test CA'): CrJsonManifestEntry {
  // c2pa-rs crJSON shape: signature.certificateInfo.{subject,issuer} are DN
  // objects keyed by CN/O/OU/etc. The crjson.ts getSignatureInfo helper
  // pulls common_name from `subject.CN` (not from a top-level field).
  return {
    ...m,
    signature: {
      alg: 'es256',
      certificateInfo: {
        subject: { CN: common_name },
        issuer: { CN: issuer },
      },
    },
  }
}

function withClaimGenerator(m: CrJsonManifestEntry, name: string): CrJsonManifestEntry {
  return { ...m, claim: { claim_generator_info: [{ name }] } }
}

function withCamera(m: CrJsonManifestEntry, make: string, model: string): CrJsonManifestEntry {
  return {
    ...m,
    assertions: {
      ...m.assertions,
      'stds.exif': { make, model },
    },
  }
}

function withSoftware(m: CrJsonManifestEntry, agent: string): CrJsonManifestEntry {
  return {
    ...m,
    assertions: {
      ...m.assertions,
      'c2pa.actions': {
        actions: [{ action: 'c2pa.edited', softwareAgent: agent }],
      },
    },
  }
}

function signals(traits: { inceptions?: string[]; transformations?: string[] } = {}): ManifestSignalsResult {
  const hit = (id: string): SignalHit => ({ trait: id, reportText: id, multiple: false })
  return {
    assertedBy: { CN: 'Test', O: 'Test' },
    mimeType: null,
    localInceptions: (traits.inceptions ?? []).map(hit),
    localTransformations: (traits.transformations ?? []).map(hit),
    allActionsIncluded: false,
    ingredients: [],
  }
}

// ── Origin-phrase tests ───────────────────────────────────────────────

describe('generateManifestSummary · origin phrases (signals-driven)', () => {
  it('captured media + camera info → "photo taken with a {camera}"', () => {
    const m = withCamera(withCert(manifest(), 'Pixel Camera'), 'Google', 'Pixel 8')
    const s = signals({ inceptions: ['inception:signal_capturedMedia'] })
    const r = generateManifestSummary(m, s, [], 'image/jpeg', false, true)
    expect(r.sentence).toBe('This is a photo taken with a Google Pixel 8.')
  })

  it('captured media without exif → "captured {media}"', () => {
    const m = withCert(manifest(), 'Some Camera')
    const s = signals({ inceptions: ['inception:signal_capturedMedia'] })
    const r = generateManifestSummary(m, s, [], 'image/jpeg', false, true)
    expect(r.sentence).toBe('This is a captured image.')
  })

  it('stitched capture + camera → "stitched photo taken with a {camera}"', () => {
    const m = withCamera(manifest(), 'Sony', 'A7')
    const s = signals({ inceptions: ['inception:signal_capturedMediaStitched'] })
    const r = generateManifestSummary(m, s, [], 'image/jpeg', false, true)
    expect(r.sentence).toBe('This is a stitched photo taken with a Sony A7.')
  })

  it('fully GenAI + creator → "{media} generated by {creator}"', () => {
    const m = withCert(manifest(), 'Adobe Firefly')
    const s = signals({ inceptions: ['inception:signal_fullyGenAIMedia'] })
    const r = generateManifestSummary(m, s, [], 'image/jpeg', false, true)
    expect(r.sentence).toBe('This is an image generated by Adobe Firefly.')
  })

  it('fully GenAI without creator → "AI-generated {media}"', () => {
    const s = signals({ inceptions: ['inception:signal_fullyGenAIMedia'] })
    const r = generateManifestSummary(manifest(), s, [], 'image/jpeg', false, true)
    expect(r.sentence).toBe('This is an AI-generated image.')
  })

  it('non-GenAI digital creation + creator → "digital artwork created with {creator}"', () => {
    const m = withSoftware(manifest(), 'Procreate')
    const s = signals({ inceptions: ['inception:signal_nonGenAIDigitalCreation'] })
    const r = generateManifestSummary(m, s, [], 'image/png', false, true)
    expect(r.sentence).toBe('This is a digital artwork created with Procreate.')
  })

  it('blank canvas → digital artwork branch', () => {
    const m = withSoftware(manifest(), 'Photoshop')
    const s = signals({ inceptions: ['inception:signal_blankCanvas'] })
    const r = generateManifestSummary(m, s, [], 'image/png', false, true)
    expect(r.sentence).toBe('This is a digital artwork created with Photoshop.')
  })

  it('screen capture → "screen capture"', () => {
    const s = signals({ inceptions: ['inception:signal_screenCaptureMayContainGenAI'] })
    const r = generateManifestSummary(manifest(), s, [], 'image/png', false, true)
    expect(r.sentence).toBe('This is a screen capture.')
  })

  it('partly GenAI → "{media} composed by {creator}"', () => {
    const m = withCert(manifest(), 'Some Editor')
    const s = signals({ inceptions: ['inception:signal_partlyGenAICreation'] })
    const r = generateManifestSummary(m, s, [], 'image/jpeg', false, true)
    expect(r.sentence).toBe('This is an image composed by Some Editor.')
  })

  it('no signals fired + creator → generic "{media} from {creator}" fallback', () => {
    const m = withCert(manifest(), 'Pixel Camera')
    const s = signals()
    const r = generateManifestSummary(m, s, [], 'image/jpeg', false, true)
    expect(r.sentence).toBe('This is an image from Pixel Camera.')
  })

  it('no signals + no creator → bare "{media}" fallback', () => {
    const s = signals()
    const r = generateManifestSummary(manifest(), s, [], 'image/jpeg', false, true)
    expect(r.sentence).toBe('This is an image.')
  })

  it('signals=null behaves the same as no-signals fallback', () => {
    const m = withCert(manifest(), 'Pixel Camera')
    const r = generateManifestSummary(m, null, [], 'image/jpeg', false, true)
    expect(r.sentence).toBe('This is an image from Pixel Camera.')
  })
})

// ── Modification-phrase tests ─────────────────────────────────────────

describe('generateManifestSummary · modification phrases', () => {
  it('editorial AI overrides editorial non-AI', () => {
    const m = withSoftware(manifest(), 'Photoshop')
    const s = signals({
      inceptions: ['inception:signal_capturedMedia'],
      transformations: [
        'transformation:signal_editorialAI',
        'transformation:signal_editorialNonAI',
      ],
    })
    const r = generateManifestSummary(m, s, [], 'image/jpeg', false, true)
    expect(r.sentence).toContain('modified using generative AI')
    expect(r.sentence).not.toContain('edited in')
  })

  it('editorial possibly-GenAI also surfaces as "modified using generative AI"', () => {
    const s = signals({
      inceptions: ['inception:signal_capturedMedia'],
      transformations: ['transformation:signal_editorialPossiblyGenAI'],
    })
    const r = generateManifestSummary(manifest(), s, [], 'image/jpeg', false, true)
    expect(r.sentence).toContain('modified using generative AI')
  })

  it('editorial non-AI + tools → "edited in {tool1} and {tool2}"', () => {
    const m = manifest({
      assertions: {
        'c2pa.actions': {
          actions: [
            { action: 'c2pa.edited', softwareAgent: 'Photoshop' },
            { action: 'c2pa.filtered', softwareAgent: 'Lightroom' },
          ],
        },
      },
    })
    const s = signals({
      inceptions: ['inception:signal_capturedMedia'],
      transformations: ['transformation:signal_editorialNonAI'],
    })
    const r = generateManifestSummary(m, s, [], 'image/jpeg', false, true)
    expect(r.sentence).toContain('edited in Photoshop and Lightroom')
  })

  it('editorial non-AI without tool names → bare "edited"', () => {
    const s = signals({
      inceptions: ['inception:signal_capturedMedia'],
      transformations: ['transformation:signal_editorialNonAI'],
    })
    const r = generateManifestSummary(manifest(), s, [], 'image/jpeg', false, true)
    expect(r.sentence).toContain('edited')
    expect(r.sentence).not.toContain('edited in')
  })

  it('non-editorial signal → "converted to a different format"', () => {
    const s = signals({
      inceptions: ['inception:signal_capturedMedia'],
      transformations: ['transformation:signal_nonEditorial'],
    })
    const r = generateManifestSummary(manifest(), s, [], 'image/jpeg', false, true)
    expect(r.sentence).toContain('converted to a different format')
  })
})

// ── Untrusted branch ──────────────────────────────────────────────────

describe('generateManifestSummary · untrusted', () => {
  it('untrusted asset uses claim-generator + signed-by, ignoring signals', () => {
    const m = withClaimGenerator(withCert(manifest(), 'Some CN'), 'My App')
    // Even with strong signals, untrusted branch wins.
    const s = signals({ inceptions: ['inception:signal_fullyGenAIMedia'] })
    const r = generateManifestSummary(m, s, [], 'image/jpeg', false, false)
    expect(r.sentence).toBe('This is an image from My App signed by Some CN.')
  })
})

// ── Footnote details ──────────────────────────────────────────────────

describe('generateManifestSummary · details', () => {
  it('lists certificate issuer and ingredient count', () => {
    const m = withCert(manifest(), 'Pixel Camera', 'C2PA CA Inc')
    const s = signals({ inceptions: ['inception:signal_capturedMedia'] })
    const r = generateManifestSummary(
      m,
      s,
      [{ title: 'src.jpg', document_id: 'a', instance_id: 'b' }],
      'image/jpeg',
      false,
      true,
    )
    expect(r.details).toContain('Certificate issued by C2PA CA Inc')
    expect(r.details).toContain('Based on 1 source asset')
  })

  it('pluralises source asset count > 1', () => {
    const ingredients = [
      { title: 'a.jpg', document_id: '1', instance_id: 'a' },
      { title: 'b.jpg', document_id: '2', instance_id: 'b' },
    ]
    const r = generateManifestSummary(manifest(), signals(), ingredients, 'image/jpeg', false, true)
    expect(r.details).toContain('Based on 2 source assets')
  })
})

// ── Grammar / composition ─────────────────────────────────────────────

describe('generateManifestSummary · grammar', () => {
  it('uses "an" before image and "a" before video/audio', () => {
    const r1 = generateManifestSummary(manifest(), null, [], 'image/jpeg', false, true)
    expect(r1.sentence).toBe('This is an image.')
    const r2 = generateManifestSummary(manifest(), null, [], 'video/mp4', false, true)
    expect(r2.sentence).toBe('This is a video.')
    const r3 = generateManifestSummary(manifest(), null, [], 'audio/mpeg', false, true)
    expect(r3.sentence).toBe('This is an audio file.')
  })

  it('joins origin + one modification with a comma', () => {
    const m = withCamera(manifest(), 'Pixel', '')
    const s = signals({
      inceptions: ['inception:signal_capturedMedia'],
      transformations: ['transformation:signal_editorialAI'],
    })
    const r = generateManifestSummary(m, s, [], 'image/jpeg', false, true)
    expect(r.sentence).toBe('This is a photo taken with a Pixel camera, modified using generative AI.')
  })

  it('joins two modifications with " and "', () => {
    const m = withSoftware(manifest(), 'Photoshop')
    const s = signals({
      inceptions: ['inception:signal_capturedMedia'],
      transformations: [
        'transformation:signal_editorialNonAI',
        'transformation:signal_nonEditorial',
      ],
    })
    const r = generateManifestSummary(m, s, [], 'image/jpeg', false, true)
    expect(r.sentence).toBe(
      'This is a captured image, edited in Photoshop and converted to a different format.',
    )
  })

  it('returns empty summary when manifest is null', () => {
    const r = generateManifestSummary(null, null, [], 'image/jpeg', false, true)
    expect(r).toEqual({ sentence: '', details: [] })
  })
})
