/**
 * Build a one-line, human-readable summary of a C2PA manifest:
 *   "This is an image taken with a Pixel Camera, edited in Adobe Photoshop."
 *
 * The detection layer (what kind of asset is this? was it AI-generated? was
 * it edited?) is sourced from the **signals rubric**
 * (`public/rubrics/asset-rubric-signals-local.yml`) so the truth source is
 * the same YAML the Conformance TF maintains. This file only handles the
 * narrative composition: picking templates, joining clauses, getting
 * grammar right, and pulling a few precision fields (camera make/model,
 * editing-software names) that the rubric doesn't return.
 *
 * To regenerate the input `signals: ManifestSignalsResult`, run the signals
 * rubric via `evaluatePerManifest()` (see `lib/rubrics/perManifest.ts`).
 */

import type { CrJsonManifestEntry, CrJsonIngredientItem } from './types'
import {
  getAssertionDataByLabel,
  getAssertionsList,
  getClaimInfo,
  getSignatureInfo,
} from './crjson'
import type { ManifestSignalsResult } from './rubrics/types'

// Signal ids exposed by `asset-rubric-signals-local.yml`. Centralised here
// so a typo or upstream rename surfaces as a single point of change.
const INCEPTION = {
  BLANK_CANVAS: 'inception:signal_blankCanvas',
  CAPTURED_MEDIA: 'inception:signal_capturedMedia',
  CAPTURED_MEDIA_STITCHED: 'inception:signal_capturedMediaStitched',
  COMPOSITION_MAY_GENAI: 'inception:signal_compositionMayContainGenAI',
  FULLY_GENAI: 'inception:signal_fullyGenAIMedia',
  UNKNOWN_PROVENANCE: 'inception:signal_mediaUnknownProvenance',
  NON_GENAI_DIGITAL_CREATION: 'inception:signal_nonGenAIDigitalCreation',
  PARTLY_GENAI: 'inception:signal_partlyGenAICreation',
  SCREEN_CAPTURE_MAY_GENAI: 'inception:signal_screenCaptureMayContainGenAI',
} as const

const TRANSFORMATION = {
  EDITORIAL_AI: 'transformation:signal_editorialAI',
  EDITORIAL_NON_AI: 'transformation:signal_editorialNonAI',
  EDITORIAL_POSSIBLY_GENAI: 'transformation:signal_editorialPossiblyGenAI',
  NON_EDITORIAL: 'transformation:signal_nonEditorial',
} as const

export interface ManifestSummary {
  /** The composed sentence, capitalised and terminated with a period. */
  sentence: string
  /** Footnote-style facts (e.g. "Certificate issued by …"). */
  details: string[]
}

/**
 * Compose the summary. Pure function; all inputs explicit.
 *
 * `signals` carries the per-manifest result for THIS manifest from the
 * signals rubric. When the caller can't load the rubric (e.g. offline /
 * dev fallback), pass `null` and we'll do a minimal "{a/an} {media} from
 * {signer}" fallback that never claims a property the rubric would.
 */
export function generateManifestSummary(
  manifest: CrJsonManifestEntry | null | undefined,
  signals: ManifestSignalsResult | null,
  ingredients: CrJsonIngredientItem[],
  mimeType: string,
  usedITL: boolean = false,
  isTrusted: boolean = true,
): ManifestSummary {
  if (!manifest) return { sentence: '', details: [] }

  const mediaWord = getMediaWord(mimeType)
  const article = articleFor(mediaWord)
  const signerName = getSignerName(manifest, usedITL)

  const parts: string[] = []
  const details: string[] = []

  if (!isTrusted) {
    parts.push(buildUntrustedOrigin(manifest, mediaWord, article))
  } else {
    parts.push(buildOriginPhrase(manifest, signals, mediaWord, article, signerName))
    const mods = buildModificationPhrases(manifest, signals)
    if (mods.length > 0) parts.push(joinAnd(mods))
  }

  // Footnote: signing certificate issuer.
  const issuer = getSignatureInfo(manifest)?.issuer
  if (issuer) details.push(`Certificate issued by ${issuer}`)

  // Footnote: ingredient count.
  const n = ingredients?.length ?? 0
  if (n > 0) details.push(`Based on ${n} source asset${n > 1 ? 's' : ''}`)

  return { sentence: composeSentence(parts), details }
}

// ── Origin phrase ─────────────────────────────────────────────────────

function buildUntrustedOrigin(
  manifest: CrJsonManifestEntry,
  mediaWord: string,
  article: string,
): string {
  const claimGenerator = getClaimGeneratorName(manifest)
  const commonName = getCommonName(manifest)
  let phrase = `This is ${article} ${mediaWord}`
  if (claimGenerator) phrase += ` from ${claimGenerator}`
  if (commonName) phrase += ` signed by ${commonName}`
  return phrase
}

function buildOriginPhrase(
  manifest: CrJsonManifestEntry,
  signals: ManifestSignalsResult | null,
  mediaWord: string,
  article: string,
  signerName: string,
): string {
  const has = makeHas(signals)
  const editingSoftware = getEditingSoftware(manifest)
  const creator = editingSoftware[0] || signerName

  // Fully GenAI overrides everything else — the asset *is* AI output.
  if (has(INCEPTION.FULLY_GENAI)) {
    return creator
      ? `This is ${article} ${mediaWord} generated by ${creator}`
      : `This is an AI-generated ${mediaWord}`
  }

  // Captured media (with optional camera precision from EXIF).
  if (has(INCEPTION.CAPTURED_MEDIA) || has(INCEPTION.CAPTURED_MEDIA_STITCHED)) {
    const camera = getCameraInfo(manifest)
    if (camera) {
      const stitched = has(INCEPTION.CAPTURED_MEDIA_STITCHED)
      return stitched
        ? `This is a stitched photo taken with a ${camera}`
        : `This is a photo taken with a ${camera}`
    }
    return `This is a captured ${mediaWord}`
  }

  // Screen capture (rubric framing: "may contain GenAI"); we keep it short.
  if (has(INCEPTION.SCREEN_CAPTURE_MAY_GENAI)) {
    return `This is a screen capture`
  }

  // Hand-crafted digital art / blank canvas / non-GenAI digital creation.
  if (has(INCEPTION.NON_GENAI_DIGITAL_CREATION) || has(INCEPTION.BLANK_CANVAS)) {
    return creator
      ? `This is a digital artwork created with ${creator}`
      : `This is a digital artwork`
  }

  // Composite with GenAI mixed in — the asset isn't fully synthetic but is
  // partly so. Sentence stays neutral; the modification clause carries the
  // "uses GenAI" detail.
  if (has(INCEPTION.PARTLY_GENAI) || has(INCEPTION.COMPOSITION_MAY_GENAI)) {
    return creator
      ? `This is ${article} ${mediaWord} composed by ${creator}`
      : `This is ${article} composed ${mediaWord}`
  }

  // Generic fallback — no inception signal fired. We say what we can without
  // claiming the asset is anything specific.
  return creator
    ? `This is ${article} ${mediaWord} from ${creator}`
    : `This is ${article} ${mediaWord}`
}

// ── Modification phrases ──────────────────────────────────────────────

function buildModificationPhrases(
  manifest: CrJsonManifestEntry,
  signals: ManifestSignalsResult | null,
): string[] {
  const has = makeHas(signals)
  const phrases: string[] = []

  // GenAI usage takes precedence over editorial-non-AI: if both fire, the
  // GenAI signal is the one we want to surface.
  if (has(TRANSFORMATION.EDITORIAL_AI) || has(TRANSFORMATION.EDITORIAL_POSSIBLY_GENAI)) {
    phrases.push('modified using generative AI')
  } else if (has(TRANSFORMATION.EDITORIAL_NON_AI)) {
    const tools = getEditingSoftware(manifest).slice(0, 2).join(' and ')
    phrases.push(tools ? `edited in ${tools}` : 'edited')
  }

  if (has(TRANSFORMATION.NON_EDITORIAL)) {
    phrases.push('converted to a different format')
  }

  return phrases
}

// ── Signal lookup helper ──────────────────────────────────────────────

/**
 * Returns a closure `has(traitId)` that's true when the signals rubric
 * fired that trait on this manifest. When `signals` is null (rubric not
 * loaded), every check returns false — the generic fallback then takes
 * over so we never make claims we can't back up.
 */
function makeHas(signals: ManifestSignalsResult | null) {
  if (!signals) return () => false
  // Cache the union once; `has()` is called many times per render.
  const traits = new Set<string>([
    ...signals.localInceptions.map((s) => s.trait),
    ...signals.localTransformations.map((s) => s.trait),
  ])
  return (id: string) => traits.has(id)
}

// ── Manifest field extractors (precision the rubric doesn't carry) ────

interface AssertionData {
  digitalSourceType?: string
  make?: string
  model?: string
  softwareAgent?: string | { name?: string }
  actions?: Array<{
    action?: string
    softwareAgent?: string | { name?: string }
  }>
}

function getAssertionData(manifest: CrJsonManifestEntry, label: string): AssertionData | null {
  return (getAssertionDataByLabel(manifest, label) as AssertionData | undefined) ?? null
}

/** Names of every `softwareAgent` referenced from any action. Order-preserving, deduplicated. */
function getEditingSoftware(manifest: CrJsonManifestEntry): string[] {
  const tools = new Set<string>()
  // Collect from all assertions whose payload looks like an actions list.
  for (const { data } of getAssertionsList(manifest)) {
    const actions = (data as AssertionData)?.actions
    if (!Array.isArray(actions)) continue
    for (const a of actions) {
      const name = softwareAgentName(a.softwareAgent)
      if (name) tools.add(name)
    }
  }
  // Also check the `c2pa.actions` shape directly in case the iterator missed it.
  const actionsAssertion = getAssertionData(manifest, 'c2pa.actions')
  if (actionsAssertion?.actions) {
    for (const a of actionsAssertion.actions) {
      const name = softwareAgentName(a.softwareAgent)
      if (name) tools.add(name)
    }
  }
  return [...tools]
}

function softwareAgentName(agent: AssertionData['softwareAgent']): string {
  if (!agent) return ''
  return cleanAgentName(typeof agent === 'string' ? agent : (agent.name ?? ''))
}

/** Strip `Tool/version` and `Tool 1.0.0` suffixes; trim whitespace. */
function cleanAgentName(name: string): string {
  if (!name) return ''
  return name.split('/')[0].trim()
}

/**
 * Best-effort camera identification from any assertion that carries
 * `make`/`model`. We scan all assertions because the field appears under
 * various labels (`stds.exif`, `c2pa.exif`, etc.) and we don't want to
 * hardcode a specific one.
 */
function getCameraInfo(manifest: CrJsonManifestEntry): string {
  for (const { data } of getAssertionsList(manifest)) {
    const d = data as AssertionData
    if (!d?.make && !d?.model) continue
    const make = d.make ?? ''
    const model = d.model ?? ''
    if (make && model) return `${make} ${model}`
    if (make) return `${make} camera`
    if (model) return model
  }
  return ''
}

// ── Identity / signer extractors ──────────────────────────────────────

function getSignerName(manifest: CrJsonManifestEntry, usedITL: boolean): string {
  // When the ITL signed the cert, prefer the claim-generator's friendly
  // name over the cert CN — the CN is often the ITL's own identity, not
  // the asset's creator.
  if (usedITL) {
    const generator = getClaimInfo(manifest)?.claim_generator_info?.[0]?.name
    if (generator) return cleanAgentName(generator)
  }
  return getSignatureInfo(manifest)?.common_name ?? ''
}

function getClaimGeneratorName(manifest: CrJsonManifestEntry): string {
  const name = getClaimInfo(manifest)?.claim_generator_info?.[0]?.name
  return name ? cleanAgentName(name) : ''
}

function getCommonName(manifest: CrJsonManifestEntry): string {
  return getSignatureInfo(manifest)?.common_name ?? ''
}

// ── Grammar / composition helpers ─────────────────────────────────────

function getMediaWord(mimeType: string): string {
  if (mimeType.startsWith('image/')) return 'image'
  if (mimeType.startsWith('video/')) return 'video'
  if (mimeType.startsWith('audio/')) return 'audio file'
  if (mimeType === 'application/pdf') return 'document'
  return 'file'
}

/** Pick `a` vs `an` based on the next word's leading sound. */
function articleFor(nextWord: string): string {
  return /^[aeiou]/i.test(nextWord) ? 'an' : 'a'
}

function joinAnd(items: string[]): string {
  if (items.length <= 1) return items[0] ?? ''
  if (items.length === 2) return `${items[0]} and ${items[1]}`
  return `${items.slice(0, -1).join(', ')}, and ${items[items.length - 1]}`
}

function composeSentence(parts: string[]): string {
  if (parts.length === 0) return ''
  let s: string
  if (parts.length === 1) s = parts[0]
  else if (parts.length === 2) s = `${parts[0]}, ${parts[1]}`
  else s = `${parts.slice(0, -1).join(', ')}, and ${parts[parts.length - 1]}`
  return s.charAt(0).toUpperCase() + s.slice(1) + '.'
}
