/**
 * Parameterized golden-parity test: for every fixture triple copied from
 * upstream (`<name>.json` + `<name>.conformance.json` + `<name>.signals.json`),
 * verify that our TS evaluators produce results that agree with the Python
 * reference on every trait the fixture covers.
 *
 * Fixtures are stored under `__fixtures__/` and were generated by
 * `c2pa_conformance_rubric_evaluator.py` (0.1 / Spec-2.2 rubric) and
 * `c2pa_signals_rubric_evaluator.py` (signals-local rubric) respectively.
 *
 * Assertion shape notes:
 *   - Conformance: subset-match. Every trait in the fixture's
 *     `true` / `false` buckets must resolve to the same outcome and
 *     reportText on our side. Rubric statements added after the fixture
 *     was generated are ignored (forward-compatible) — that's fine
 *     because the upstream rubric has grown past its fixtures (see e.g.
 *     `thumbnail_location` which post-dates every fixture).
 *   - Signals: exact-match, field by field, in fixture order.
 */

import { describe, expect, it } from 'vitest'
import fs from 'node:fs'
import path from 'node:path'
import type { CrJson } from '../crjson'
import { parseRubricYaml } from './loader'
import { evaluateRubric } from './evaluate'
import { evaluatePerManifest } from './perManifest'
import type { RubricResult } from './types'

const FIXTURE_DIR = path.resolve(__dirname, '__fixtures__')
const CONFORMANCE_RUBRIC_PATH = path.resolve(
  __dirname,
  '../../../public/rubrics/asset-rubric-conformance0.1-spec2.2.yml',
)
const SIGNALS_RUBRIC_PATH = path.resolve(
  __dirname,
  '../../../public/rubrics/asset-rubric-signals-local.yml',
)

// Parse the rubrics once so we're not paying YAML parse cost per fixture.
const conformanceRubric = parseRubricYaml(
  fs.readFileSync(CONFORMANCE_RUBRIC_PATH, 'utf8'),
  'asset-rubric-conformance0.1-spec2.2.yml',
)
const signalsRubric = parseRubricYaml(
  fs.readFileSync(SIGNALS_RUBRIC_PATH, 'utf8'),
  'asset-rubric-signals-local.yml',
)

// Discover fixtures by looking for `<name>.json` files that also have
// companion `.conformance.json` and `.signals.json` siblings. This keeps
// the test list self-maintaining when new fixtures land in the directory.
function discoverFixtureNames(): string[] {
  const all = fs.readdirSync(FIXTURE_DIR)
  const baseInputs = all.filter(
    (f) => f.endsWith('.json') && !f.endsWith('.conformance.json') && !f.endsWith('.signals.json'),
  )
  return baseInputs
    .map((f) => f.replace(/\.json$/, ''))
    .filter(
      (name) =>
        all.includes(`${name}.conformance.json`) && all.includes(`${name}.signals.json`),
    )
    .sort()
}

const FIXTURE_NAMES = discoverFixtureNames()

// ── Conformance fixture parity ────────────────────────────────────────

interface ConformanceFixture {
  rubricName: string
  rubricVersion: string
  true: Record<string, Array<{ trait: string; reportText: string }>>
  false: Record<string, Array<{ trait: string; reportText: string }>>
}

/** trait → { outcome, reportText } lookup, flattened across all categories. */
function traitIndex(
  result: RubricResult,
): Map<string, { outcome: 'true' | 'false' | 'error'; reportText: string }> {
  const out = new Map<string, { outcome: 'true' | 'false' | 'error'; reportText: string }>()
  for (const s of result.statements) {
    const trait = s.id.includes(':') ? s.id.split(':').slice(1).join(':') : s.id
    const outcome: 'true' | 'false' | 'error' =
      s.passed === true ? 'true' : s.passed === false ? 'false' : 'error'
    out.set(`${s.category}:${trait}`, { outcome, reportText: s.message })
  }
  return out
}

describe('conformance rubric · parameterized golden parity (0.1 spec 2.2)', () => {
  it(`discovered at least the original capture fixture`, () => {
    // Cheap sanity check so a broken discover doesn't silently skip all tests.
    expect(FIXTURE_NAMES).toContain('capture')
    expect(FIXTURE_NAMES.length).toBeGreaterThanOrEqual(15)
  })

  for (const name of FIXTURE_NAMES) {
    it(`${name} · every fixture trait matches our evaluator`, () => {
      const input = JSON.parse(
        fs.readFileSync(path.join(FIXTURE_DIR, `${name}.json`), 'utf8'),
      ) as CrJson
      const expected = JSON.parse(
        fs.readFileSync(path.join(FIXTURE_DIR, `${name}.conformance.json`), 'utf8'),
      ) as ConformanceFixture

      const result = evaluateRubric(conformanceRubric, input, {
        rubricId: 'asset-conformance-0.1-spec2.2',
      })
      expect(result.rubricName).toBe(expected.rubricName)
      expect(result.rubricVersion).toBe(expected.rubricVersion)

      const index = traitIndex(result)

      const mismatches: string[] = []
      const check = (
        wantOutcome: 'true' | 'false',
        buckets: ConformanceFixture['true'],
      ) => {
        for (const [category, traits] of Object.entries(buckets)) {
          for (const { trait, reportText } of traits) {
            const got = index.get(`${category}:${trait}`)
            if (!got) {
              mismatches.push(`  missing: ${category}:${trait}`)
              continue
            }
            if (got.outcome !== wantOutcome) {
              mismatches.push(
                `  ${category}:${trait} → outcome expected=${wantOutcome} got=${got.outcome}`,
              )
            }
            if (got.reportText !== reportText) {
              mismatches.push(
                `  ${category}:${trait} → reportText diverged\n    want: ${reportText}\n    got:  ${got.reportText}`,
              )
            }
          }
        }
      }
      check('true', expected.true)
      check('false', expected.false)

      expect(mismatches, `parity diffs for ${name}:\n${mismatches.join('\n')}`).toEqual([])
    })
  }
})

// ── Signals fixture parity ────────────────────────────────────────────

interface SignalsFixture {
  rubricName: string
  rubricVersion: string
  manifests: Array<{
    assertedBy: { CN: string; O: string; OU?: string }
    mimeType: string | null
    localInceptions: Array<{ trait: string; reportText: string; multiple: boolean }>
    localTransformations: Array<{ trait: string; reportText: string; multiple: boolean }>
    allActionsIncluded: boolean
    ingredients: Array<{ index: number; relationship?: string }>
  }>
}

describe('signals rubric · parameterized golden parity (local)', () => {
  for (const name of FIXTURE_NAMES) {
    it(`${name} · per-manifest signals match the reference exactly`, () => {
      const input = JSON.parse(
        fs.readFileSync(path.join(FIXTURE_DIR, `${name}.json`), 'utf8'),
      ) as CrJson
      const expected = JSON.parse(
        fs.readFileSync(path.join(FIXTURE_DIR, `${name}.signals.json`), 'utf8'),
      ) as SignalsFixture

      const result = evaluatePerManifest(signalsRubric, input, {
        rubricId: 'asset-signals-local',
      })

      expect(result.rubricName).toBe(expected.rubricName)
      expect(result.rubricVersion).toBe(expected.rubricVersion)
      expect(result.manifests).toHaveLength(expected.manifests.length)

      for (let i = 0; i < expected.manifests.length; i++) {
        const want = expected.manifests[i]
        const got = result.manifests[i]
        expect(got.assertedBy, `${name} manifest[${i}] assertedBy`).toEqual(want.assertedBy)
        expect(got.mimeType, `${name} manifest[${i}] mimeType`).toEqual(want.mimeType)
        expect(got.allActionsIncluded, `${name} manifest[${i}] allActionsIncluded`).toEqual(
          want.allActionsIncluded,
        )
        expect(got.localInceptions, `${name} manifest[${i}] localInceptions`).toEqual(
          want.localInceptions,
        )
        expect(
          got.localTransformations,
          `${name} manifest[${i}] localTransformations`,
        ).toEqual(want.localTransformations)
        expect(got.ingredients, `${name} manifest[${i}] ingredients`).toEqual(want.ingredients)
      }
    })
  }
})
